### ISSUE TITLE
Neue Playlist anlegen

### ISSUE THREAD

**Issue by mstrauch** [mstrauch/got-website#10]
Das Anlegen einer neuen Playlist (siehe Abbildung 11) ist sehr einfach gehalten: der Name soll in die Textbox eingegeben werden und nach Klick auf  Anlegen  soll die Liste angelegt und der Benutzer auf die (aktualisierte) Hauptseite gelei- tet werden. Wenn eine Playlist schon existiert, soll dieser Fehler still ignoriert werden.

**Comment by Twivex** [comment]
Template erstellt und Model erweitert
